#################################
#################################
## Deploy Release Docker Image ##
#################################
#################################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

##########################################
# Start the job upon a published release #
##########################################
on:
  # Start when a release is published
  push:
    branches:
      - 'main'

###############
# Set the Job #
###############
jobs:
  deploy:
    # Name the Job
    name: Deploy Docker Image - Release - standard
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    timeout-minutes: 60

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      ########################
      # Get the current date #
      ########################
      - name: Get current date
        run: echo "BUILD_DATE=\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\" >> ${GITHUB_ENV}"

      ########################
      # Setup Docker build X #
      ########################
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1.6.0

      ######################################
      # Login to GitHub Container registry #
      ######################################
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      ###########################
      # Get the current release #
      ###########################
      - name: Get current Release number
        # shellcheck disable=SC2062
        run: |
          echo "RELEASE_VERSION=$(echo ${{ github.event.release.name }} \
          | grep -E -o "v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+")" \
          >> "${GITHUB_ENV}"
      ################
      # Docker cache #
      ################
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-standard
          restore-keys: |
            ${{ runner.os }}-single-buildx
      ###########################################
      # Build and Push containers to registries #
      ###########################################
      - name: Build and push - Standard
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
          push: true
          tags: |
            ghcr.io/peaksmp/website
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      #############
      # Fix Cache #
      #############
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
